export const NOTIFICATION_TYPES = Object.freeze({
  NEW_EVENT: 'NEW_EVENT',
  NEW_JOB: 'NEW_JOB',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',
  COORDINATOR_APPROVAL: 'COORDINATOR_APPROVAL',
  ENTREPRENEURSHIP_APPROVAL: 'ENTREPRENEURSHIP_APPROVAL',
  INCUBATION_APPROVAL: 'INCUBATION_APPROVAL',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  CHAT_MESSAGE: 'CHAT_MESSAGE'
});
